/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appIndexImport } from './routes/(app)/index'
import { Route as authSignupImport } from './routes/(auth)/signup'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as appProfileImport } from './routes/(app)/profile'
import { Route as appProductsImport } from './routes/(app)/products'
import { Route as appInvoicesImport } from './routes/(app)/invoices'
import { Route as appDashboardImport } from './routes/(app)/dashboard'
import { Route as appCustomersImport } from './routes/(app)/customers'
import { Route as appInvoiceIndexImport } from './routes/(app)/invoice/index'
import { Route as appInvoiceInvoiceIdImport } from './routes/(app)/invoice/$invoiceId'

// Create/Update Routes

const appIndexRoute = appIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authSignupRoute = authSignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const appProfileRoute = appProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const appProductsRoute = appProductsImport.update({
  path: '/products',
  getParentRoute: () => rootRoute,
} as any)

const appInvoicesRoute = appInvoicesImport.update({
  path: '/invoices',
  getParentRoute: () => rootRoute,
} as any)

const appDashboardRoute = appDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const appCustomersRoute = appCustomersImport.update({
  path: '/customers',
  getParentRoute: () => rootRoute,
} as any)

const appInvoiceIndexRoute = appInvoiceIndexImport.update({
  path: '/invoice/',
  getParentRoute: () => rootRoute,
} as any)

const appInvoiceInvoiceIdRoute = appInvoiceInvoiceIdImport.update({
  path: '/invoice/$invoiceId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/customers': {
      preLoaderRoute: typeof appCustomersImport
      parentRoute: typeof rootRoute
    }
    '/(app)/dashboard': {
      preLoaderRoute: typeof appDashboardImport
      parentRoute: typeof rootRoute
    }
    '/(app)/invoices': {
      preLoaderRoute: typeof appInvoicesImport
      parentRoute: typeof rootRoute
    }
    '/(app)/products': {
      preLoaderRoute: typeof appProductsImport
      parentRoute: typeof rootRoute
    }
    '/(app)/profile': {
      preLoaderRoute: typeof appProfileImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signup': {
      preLoaderRoute: typeof authSignupImport
      parentRoute: typeof rootRoute
    }
    '/(app)/': {
      preLoaderRoute: typeof appIndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/invoice/$invoiceId': {
      preLoaderRoute: typeof appInvoiceInvoiceIdImport
      parentRoute: typeof rootRoute
    }
    '/(app)/invoice/': {
      preLoaderRoute: typeof appInvoiceIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  appCustomersRoute,
  appDashboardRoute,
  appInvoicesRoute,
  appProductsRoute,
  appProfileRoute,
  authLoginRoute,
  authSignupRoute,
  appIndexRoute,
  appInvoiceInvoiceIdRoute,
  appInvoiceIndexRoute,
])

/* prettier-ignore-end */
